#!/bin/bash

function die {
  echo "ERROR: ${1}"
  exit 1
}

case ${1} in
  start)
    /usr/local/sbin/nginx &
    while true; do inotifywait -e close_write /nginx-generated/default.conf && pkill -HUP nginx; done
    ;;
  *)
    ${1}
    ;;
esac
