#!/bin/bash

function die {
  echo "ERROR: ${1}"
  exit 1
}

function setup {
  sed "s@{{TITLE}}@${TITLE:-Etherpad}@g" -i /etherpad-lite/settings.json
  sed "s@{{SESSION_KEY}}@${SESSION_KEY:-abcdef}@g" -i /etherpad-lite/settings.json
  sed "s@{{DB_HOST}}@${POSTGRESQL_PORT_5432_TCP_ADDR}@g" -i /etherpad-lite/settings.json
  sed "s@{{DEFAULT_PAD_TEXT}}@$${DEFAULT_PAD_TEXT:-}@g" -i /etherpad-lite/settings.json
  sed "s@{{ADMIN_PW}}@${ADMIN_PW:-password}@g" -i /etherpad-lite/settings.json
}

case ${1} in
  start)
    setup
    cd /etherpad-lite && /usr/bin/node node_modules/ep_etherpad-lite/node/server.js
    ;;
  *)
    ${1}
    ;;
esac
