#!/bin/bash

# 'docker stop' signal handeling.
trap '[ -e "/opt/splunk/var/run/splunk/splunkweb.pid" ] && /opt/splunk/bin/splunk stop; exit 0' SIGTERM

# Using splunk --nodaemon isnt working correctly and will never start the web-service..
/opt/splunk/bin/splunk start && tail -f /opt/splunk/var/log/splunk/splunkd.log
