#!/bin/bash

function die {
  echo "ERROR: ${1}"
  exit 1
}

function setup {
  touch /sites.conf # So nginx wont complain before its created
}

setup

case ${1} in
  start)
    supervisord -c /supervisord.conf
    ;;
  *)
    ${1}
    ;;
esac
