#!/bin/bash

function die {
  echo "ERROR: ${1}"
  exit 1
}

case ${1} in
  start)
    # Ripoff from the original run.sh with some changes and without comments:
    #  * Added "-Dgnu.io.rxtx.SerialPorts=/dev/rfxcom:/dev/zwave" to java run
    #  * Hardcoded path to /srv
    set -x
    cd /srv

    [[ -z ${ADDONS} ]] && die "You need to define some ADDONS"

    mkdir disabled_addons
    mv addons/*.jar disabled_addons/
    for addon in ${ADDONS}; do
      mv disabled_addons/${addon} addons/ || true
    done

    eclipsehome="server";
    HTTP_PORT=8080
    HTTPS_PORT=8443
    cp=$(find $eclipsehome -name "org.eclipse.equinox.launcher_*.jar" | sort | tail -1);
    echo Launching the openHAB runtime...
    java -Dgnu.io.rxtx.SerialPorts=/dev/rfxcom:/dev/zwave -Dosgi.clean=true -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Djetty.port=$HTTP_PORT -Djetty.port.ssl=$HTTPS_PORT -Djetty.home=. -Dlogback.configurationFile=configurations/logback.xml -Dfelix.fileinstall.dir=addons -Djava.library.path=lib -Djava.security.auth.login.config=./etc/login.conf -Dorg.quartz.properties=./etc/quartz.properties -Dequinox.ds.block_timeout=240000 -Dequinox.scr.waitTimeOnBlock=60000 -Dfelix.fileinstall.active.level=4 -Djava.awt.headless=true -jar $cp $* -console

    ;;
  *)
    ${1}
    ;;
esac

