#!/bin/bash

function die {
  echo "ERROR: ${1}"
  exit 1
}

function check_depending_container_connections {
  echo -n "Checking depending container connections "
  #[[ -> $DB_PORT_5432_TCP_ADDR ]] && die "No link to DB"
  echo -n "[done]"
  echo
}

function setup {
  echo "Running setup()"
}

setup

case ${1} in
  start)
    check_depending_container_connections
    /usr/bin/supervisord -n -c /etc/supervisord.conf -e ${LOGLEVEL:-error}
    ;;

  *)
    $*
    ;;
esac
