#!/bin/bash

function die {
  echo "ERROR: ${1}"
  exit 1
}

case ${1} in
  start)
    # quick and dirty.. dnsmasq reload (HUP) did not work
    dnsmasq
    while inotifywait -e close_write -r /etc/dnsmasq.d/; do pkill -9 dnsmasq && dnsmasq; done
    ;;
  *)
    ${1}
    ;;
esac

